### ISSUE TITLE
v8.1.3 (2019-02-08) causes console errors constantly

### ISSUE THREAD

**Issue by markdall** [kaminaris/MaxDps-Hunter#3]
After getting into combat I get spam over and over again how basic pet abilities must be on my action bar. I can't even put said abilities on my action bar. The only fix I've found is to revert to v8.1.1.2.

Thanks for a wonderful addon!

**Comment by pwilkowski** [comment]
Here is instruction how to put pet basic ability on YOUR action bars:
https://www.youtube.com/watch?v=J9DsrQrjrEc

Also you can disable advanced AOE in settings but its not recommended as it will just not work properly for BM. Closing

**Comment by wmill** [comment]
:-1:

**Comment by pwilkowski** [comment]
You want long answer, BM most powerful (and only worth using) aoe ability beast cleave can only hit targets near your pet. There is no other way to check how many targets are close to your pet other than putting pet basic ability on player action bars because IsActionInRange works only for player action IDs.

And I did not make it up. If you check beast cleave count auras these still requires you to do the same (read description):
https://wago.io/NkVzrnz6M
https://wago.io/Byos8GKBZ

Otherwise on mechatorque you would see a lot of multishots because of these robots that roams around. And a lot more issues in other places with standard AOE recognition.

**Comment by markdall** [comment]
I believe you, thanks so much! Much obliged!
